apiVersion: v1
kind: Service
metadata:
  name: amr-api-svc-dev
  namespace: amr-portal-ns-dev
  labels:
    ensembl.platform.app.name: amr-api-dev
spec:
  selector:
    ensembl.platform.app.name: amr-api-dev
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 32027
