apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ensembl.platform.app.name: amr
  name: amr-portal-pv-claim-data-dev
  namespace: amr-portal-ns-dev
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: amr-portal-data-pv-dev
  storageClassName: ""
