apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: amr-portal-nginx
  name: amr-portal-dev
  namespace: amr-portal-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      ensembl.platform.app.name: amr-portal-nginx
  template:
    metadata:
      labels:
        ensembl.platform.app.name: amr-portal-nginx
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: DOCKER_IMAGE
        imagePullPolicy: Always
        name: amr-portal-nginx
        env:
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: amr-frontend-configmap-dev
              key: VITE_API_BASE_URL
        ports:
        - containerPort: 8000
          protocol: TCP