apiVersion: v1
kind: ConfigMap
metadata:
  name: amr-frontend-runtime-config
  namespace: amr-portal-dev
data:
  runtime-config.js: |
    window.__AMR_CONFIG__ = {
      apiBaseUrl: "http://hh-rke-wp-webadmin-52-master-1.caas.ebi.ac.uk:32027/api"
    };
