apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend
- frontend/nginx
configMapGenerator:
- name: shared-image-config
  envs:
  - images.env
generatorOptions:
  disableNameSuffixHash: true
replacements:
- source:
    kind: ConfigMap
    name: shared-image-config
    fieldPath: data.BACKEND_IMAGE
  targets:
  - select:
      kind: Deployment
      name: amr-deployment
    fieldPaths:
    - spec.template.spec.containers.0.image
- source:
    kind: ConfigMap
    name: shared-image-config
    fieldPath: data.FRONTEND_IMAGE
  targets:
  - select:
      kind: Deployment
      name: amr-portal-nginx-deployment-dev
    fieldPaths:
    - spec.template.spec.containers.0.image
