apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amr-portal-assets-pvc-dev
  namespace: amr-portal-ns-dev
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: amr-portal-assets-pv-dev
  storageClassName: ""
