apiVersion: v1
kind: Service
metadata:
  name: amr-frontend-svc-prod
  namespace: amr-portal-ns-prod
  labels:
    ensembl.platform.app.name: amr-portal-prod
spec:
  selector:
    ensembl.platform.app.name: amr-portal-prod
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 32026
