apiVersion: apps/v1
kind: Deployment
metadata:
  name: amr-api-prod
  namespace: amr-portal-ns-prod
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      ensembl.platform.app.name: amr-api-prod
  template:
    metadata:
      labels:
        ensembl.platform.app.name: amr-api-prod
    spec:
      imagePullSecrets:
        - name: containers-pull-secret
      containers:
        - name: amr-api-prod
          args: ["--host", "0.0.0.0", "--port", "8000", "main:app" ]
          command: ["uvicorn"]
          envFrom:
          - configMapRef:
              name: amr-api-configmap-prod
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
          volumeMounts:
          - mountPath: /usr/data/
            name: amrdata
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
      - name: amrdata
        persistentVolumeClaim:
          claimName: amr-portal-pv-claim-data-prod
