apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ensembl.platform.app.name: amr
  name: amr-portal-pv-claim-data-prod
  namespace: amr-portal-ns-prod
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: amr-portal-data-pv-prod
  storageClassName: ""
